
package com.train.jaxws.complex.type.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Java6WS", targetNamespace = "http://server.type.complex.jaxws.train.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Java6WS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.train.jaxws.complex.type.client.UserBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething1", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething1")
    @ResponseWrapper(localName = "doSomething1Response", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething1Response")
    @Action(input = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething1Request", output = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething1Response")
    public List<UserBean> doSomething1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething2", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething2")
    @ResponseWrapper(localName = "doSomething2Response", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething2Response")
    @Action(input = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething2Request", output = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething2Response")
    public String doSomething2(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Foo> arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.train.jaxws.complex.type.client.UserBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething3", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething3")
    @ResponseWrapper(localName = "doSomething3Response", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething3Response")
    @Action(input = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething3Request", output = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething3Response")
    public UserBean doSomething3(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething4", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething4")
    @ResponseWrapper(localName = "doSomething4Response", targetNamespace = "http://server.type.complex.jaxws.train.com/", className = "com.train.jaxws.complex.type.client.DoSomething4Response")
    @Action(input = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething4Request", output = "http://server.type.complex.jaxws.train.com/Java6WS/doSomething4Response")
    public String doSomething4(
        @WebParam(name = "arg0", targetNamespace = "")
        Foo arg0);

}
