
package com.train.jaxws.tutorial.service.client.call;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderProcessService", targetNamespace = "http://jawxs.tutorial/jaxws/orderprocess")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcessService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.train.jaxws.tutorial.service.client.call.OrderBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://jawxs.tutorial/jaxws/orderprocess", className = "com.train.jaxws.tutorial.service.client.call.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://jawxs.tutorial/jaxws/orderprocess", className = "com.train.jaxws.tutorial.service.client.call.ProcessOrderResponse")
    @Action(input = "http://jawxs.tutorial/jaxws/orderprocess/OrderProcessService/processOrderRequest", output = "http://jawxs.tutorial/jaxws/orderprocess/OrderProcessService/processOrderResponse")
    public OrderBean processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderBean arg0);

}
